FROM rust:1.60
RUN rustup component add rustfmt
RUN rustup component add clippy
RUN rustup component add rust-analysis
RUN rustup component add rust-docs
RUN rustup component add rust-src
RUN rustup component add rls
