FROM rust:1.60
RUN rustup component add rustfmt --toolchain 1.60.0-x86_64-unknown-linux-gnu
RUN rustup component add clippy --toolchain 1.60.0-x86_64-unknown-linux-gnu
RUN rustup component add rust-analysis --toolchain 1.60.0-x86_64-unknown-linux-gnu
RUN rustup component add rust-docs --toolchain 1.60.0-x86_64-unknown-linux-gnu
RUN rustup component add rust-src --toolchain 1.60.0-x86_64-unknown-linux-gnu
RUN rustup component add rls --toolchain 1.60.0-x86_64-unknown-linux-gnu
